### ISSUE TITLE
Support second CD image

### ISSUE THREAD

**Issue by woachk** [ubenmackin/ACVM#18]
With the support of a second CD image, you can install Windows directly from a DVD image, with attaching https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso as a second image.

This also allows installing Windows on virtio-blk instead of NVMe.

Also, adding the virtio-rng-pci device would make sense.

**Comment by ubenmackin** [comment]
If I can get this done tonight, I will. Otherwise, I'll get it added in tomorrow.

**Comment by ubenmackin** [comment]
@woachk So I understand better, what is the use of virtio-rng-pci, as I am not familiar with this.

**Comment by woachk** [comment]
@ubenmackin it's to provide proper entropy to the guest for random number generation. (/dev/random & urandom)

**Comment by ubenmackin** [comment]
@woachk Ok, so I checked out:

https://wiki.qemu.org/Features/VirtIORNG

and I set it up as

```
-object rng-random,filename=/dev/random,id=rng0
-device virtio-rng-pci,rng=rng0
```

But it caused my Ubuntu image to not boot. It just gets stuck at "Booting Linux Kernel". Once I remove that option, it boots back up normally. Do you know if there is anything else I should be trying for this option?

**Comment by woachk** [comment]
@ubenmackin just have -device virtio-rng-pci without further options, that should work properly.
