### ISSUE TITLE
ACVM support nic bridge?

### ISSUE THREAD

**Issue by cyrus0880** [ubenmackin/ACVM#26]
hello 
i wan to use bridge mode on vm ,i want in vm ssh host (osx)

i try other vm project (vftool) by default is using the bridge mode
but i using vftool is install ubuntu only this is can ssh my main host & ping any ip address
this project networking is com.apple.vm.networking
it appears to be kernel-level NAT from a bridged interface instead of the user-level TCP/IP stuff as used in QEMU

**Comment by ubenmackin** [comment]
Please see the discussion here:

https://forums.macrumors.com/threads/success-virtualize-windows-10-for-arm-on-m1-with-alexander-grafs-qemu-hypervisor-patch.2272354/post-29426984

As ACVM is just a wrapper to qemu, any specific networking changes would need to be made to qemu itself. If such a time comes around that qemu is updated to use this framework, I will update ACVM to incorporate those options.

**Comment by cyrus0880** [comment]
thx
now just can do is waiting qemu update use this framework & macport tun/tap port to apple silicon
