### ISSUE TITLE
compile on x86_64

### ISSUE THREAD

**Issue by joske** [ubenmackin/ACVM#30]
Hi,

I'm trying to get this to work under x86_64 while waiting for my M1 macbook air to arrive. Seems it would also be useful in intel world. I have replaced the dylibs with x86_64 versions, but still getting a SIGABRT hile it's loading one of the shared libs:
#0	0x000000011acbdf7a in __abort_with_payload ()
#6	0x000000011ac63025 in _dyld_start ()

Any idea?

**Comment by ubenmackin** [comment]
@joske I no longer have x86_64 based Mac to test on. The application frontend (ACVM) is not a Universal app, but built for Apple Silicon. So I don't think you can just swap out the libs and have it work.

**Comment by joske** [comment]
I changed the target to My Mac (so x86). It compiles, but still getting the SIGABRT. Don't even know which library it's trying to load. Any idea on how to debug this?

**Comment by joske** [comment]
I am now able to start qemu standalone with aarch64 and arm64 ubuntu. I think the qemu libs are not the problem, but the sparkle thingy:

dyld: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Users/jos/Library/Developer/Xcode/DerivedData/ACVM-fectmcndczkxbpexlfiskuujbdsi/Build/Products/Debug/ACVM.app/Contents/MacOS/ACVM
  Reason: no suitable image found.  Did find:
	/Users/jos/Library/Developer/Xcode/DerivedData/ACVM-fectmcndczkxbpexlfiskuujbdsi/Build/Products/Debug/ACVM.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle: code signature in (/Users/jos/Library/Developer/Xcode/DerivedData/ACVM-fectmcndczkxbpexlfiskuujbdsi/Build/Products/Debug/ACVM.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
	/Users/jos/Library/Developer/Xcode/DerivedData/ACVM-fectmcndczkxbpexlfiskuujbdsi/Build/Products/Debug/ACVM.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle: code signature in (/Users/jos/Library/Developer/Xcode/DerivedData/ACVM-fectmcndczkxbpexlfiskuujbdsi/Build/Products/Debug/ACVM.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
	/Users/jos/Library/Developer/Xcode/DerivedData/ACVM-fectmcndczkxbpexlfiskuujbdsi/Build/Products/Debug/ACVM.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle: code signature in (/Users/jos/Library/Developer/Xcode/DerivedData/ACVM-fectmcndczkxbpexlfiskuujbdsi/Build/Products/Debug/ACVM.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
	/Users/jos/Library/Developer/Xcode/DerivedData/ACVM-fectmcndczkxbpexlfiskuujbdsi/Build/Products/Debug/ACVM.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle: stat() failed with errno=1
(lldb)

**Comment by joske** [comment]
Got it to work, turned out it was a code signing issue (I'm quite new to macOS development, linux guy). I can now start the ACVM gui, configure it, but when I try to start a VM, it crashes the qemu process (ACVM keeps running). Debugging.

**Comment by joske** [comment]
you can close this item. I've got some dirty but working code in my fork. Mostly it's changes to the QEMU command line. That version has x86_64 binaries for everything, so it can start QEMU VMs on x86. Have not yet tried to start an ARM64 VM with it.
