### ISSUE TITLE
Doesnt start Win10 image

### ISSUE THREAD

**Issue by txlpaul** [ubenmackin/ACVM#4]
Configured a new VM with an already converted qcow2 Win10/Arm image. VM doesn't start (State: Stopped). Same image runs fine on ACVM 1.04

**Comment by ubenmackin** [comment]
Please try now with the latest version. The issue was due to missing library files, that I didn't properly reference to the binaries.

**Comment by txlpaul** [comment]
Works! Thanks a lot.
